version: "3.3"
services:
  reverse-proxy: 
    image: "traefik"
    restart: always
    links:
    - "api"
    - "doc"
    - "minio"
    command:
    - "--api.insecure=true"
    - "--providers.docker=true"
    - "--providers.docker.exposedbydefault=false"
    - "--entrypoints.web.address=:80"
    - "--entrypoints.websecure.address=:443"
    - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
    - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    - "--certificatesresolvers.httpsresolver.acme.tlschallenge=true"
    - "--certificatesresolvers.httpsresolver.acme.email=${HOST_EMAIL}"
    - "--certificatesresolvers.httpsresolver.acme.storage=/letsencrypt/acme.json"
    ports:
    - 443:443
    - 80:80
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "./letsencrypt:/letsencrypt"
    depends_on:
      api:
        condition: service_started
      minio:
        condition: service_started
      doc:
        condition: service_started
  api:
    image: "ghcr.io/la-sectoblique/septotrip-api:master"
    restart: always
    links:
    - postgres
    - minio
    environment:
      NODE_ENV: production
      API_PORT: 80
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: 5432
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      S3_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      S3_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      S3_ENDPOINT: minio:9000
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.api.rule=Host(`api.${URL}`)"
    - "traefik.http.routers.api.tls=true"
    - "traefik.http.routers.api.tls.certresolver=httpsresolver"
    - "traefik.http.routers.api.entrypoints=websecure"
    - "traefik.http.services.api.loadbalancer.server.port=80"
    - "traefik.http.middlewares.cors-headers.headers.accessControlAllowOriginListRegex=(.*?)"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
  webapp:
    image: "ghcr.io/la-sectoblique/septotrip-webapp:master"
    restart: always
    links:
    - api
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.webapp.rule=Host(`${URL}`)"
    - "traefik.http.services.webapp.loadbalancer.server.port=80"
    - "traefik.http.routers.webapp.tls=true"
    - "traefik.http.routers.webapp.tls.certresolver=httpsresolver"
    - "traefik.http.routers.webapp.entrypoints=websecure"
    - "traefik.http.middlewares.cors-headers.headers.accessControlAllowOriginListRegex=(.*?)"
  postgres:
    image: "postgis/postgis"
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "--dbname=${DB_NAME}", "--host=localhost", "--username=${DB_USER}"]
      timeout: 10s
      retries: 10
  postgres-test:
    image: "postgis/postgis"
    restart: always
    ports:
    - 5433:5432
    environment:
      POSTGRES_DB: test-${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "--dbname=test-${DB_NAME}", "--host=localhost", "--username=${DB_USER}"]
      timeout: 10s
      retries: 10
  doc: 
    image: "ghcr.io/la-sectoblique/septrotrip-service:master"
    restart: always
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.doc.rule=Host(`doc.${URL}`)"
    - "traefik.http.services.doc.loadbalancer.server.port=80"
    - "traefik.http.routers.doc.tls=true"
    - "traefik.http.routers.doc.tls.certresolver=httpsresolver"
    - "traefik.http.routers.doc.entrypoints=websecure"
    - "traefik.http.middlewares.cors-headers.headers.accessControlAllowOriginListRegex=(.*?)"
  minio:
    image: minio/minio
    volumes:
    - ${MINIO_PATH}:/data
    environment:
    - MINIO_ROOT_USER=${MINIO_ROOT_USER}
    - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    - MINIO_BROWSER_REDIRECT_URL=http://stash.${URL}
    command:
    - server
    - /data
    - --console-address
    - ":9001"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.minio.service=minio"
    - "traefik.http.routers.minio.rule=Host(`files.${URL}`)"
    - "traefik.http.services.minio.loadbalancer.server.port=9000"
    - "traefik.http.routers.minio.tls=true"
    - "traefik.http.routers.minio.tls.certresolver=httpsresolver"
    - "traefik.http.routers.minio.entrypoints=websecure"
    - "traefik.http.middlewares.cors-headers.headers.accessControlAllowOriginListRegex=(.*?)"
    - "traefik.http.routers.minio-console.service=minio-console"
    - "traefik.http.routers.minio-console.rule=Host(`stash.${URL}`)"
    - "traefik.http.services.minio-console.loadbalancer.server.port=9001"
    - "traefik.http.routers.minio-console.tls=true"
    - "traefik.http.routers.minio-console.tls.certresolver=httpsresolver"
    - "traefik.http.routers.minio-console.entrypoints=websecure"