name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: wshihadeh/docker-deployment-action@v1
      name: Docker-Compose Remote Deployment
      with:
        remote_docker_host: ${{ secrets.SSH_USER }}@septotrip.com
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        stack_file_name: docker-compose.prod.yml
        copy_stack_file: 'true'
        deploy_path: /var/lib/docker-deploy/
        deployment_mode: docker-compose
        pull_images_first: 'true'
        args: up -d
